export interface ChartDataModel {
    summarizeValueCounter? : number | null,
    summarizeValueAllProductsValue? : string,
    summarizeValueAllProductsValueWhereTaxIsMonofasica? : string,
    summarizeValueAllProductsValueWhereTaxIsNormal? : string,
    summarizeValueAllProductsValueWhereTaxIsAliqZero? : string,
    valorPis? : string,
    valorCofins? : string,
    summarizeValueWhereTaxIsMonofasicaCounter? : number | null,
    summarizeValueWhereTaxIsNormalCounter? : number | null,
    summarizeValueWhereTaxIsAliqZeroCounter? : number | null,
    bonusExit? : string,
    bonusEntrance? : string,
    onusExit? : string,
    onusEntrance? : string,
    subtotalAliqZero? : string,
    subtotalMonofasica? : string,
    countNcmNull? : number | null,
    calcBaseBonus? : string,
    cofinsBonus? : string,
    pisBonus? : string,
    calcBaseOnus? : string,
    pisOnus? : string,
    cofinsOnus? : string
}